# Generated by Django 4.0.3 on 2022-03-13 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_grocery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='image',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='organic',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='groceries',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='groceries',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.grocery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
